// <auto-generated />

#nullable disable

#nullable disable
namespace FullstackMVC.Migrations
{
    using FullstackMVC.Context;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Microsoft.EntityFrameworkCore.Metadata;
    using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
    using System;

    [DbContext(typeof(CompanyContext))]
    internal partial class CompanyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FullstackMVC.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OtpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentSSN")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("StudentSSN");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FullstackMVC.Models.Course", b =>
                {
                    b.Property<int>("Num")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Num"));

                    b.Property<decimal>("Degree")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<decimal>("MinDegree")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Topic")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Num");

                    b.HasIndex("DeptId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Num = 1,
                            Degree = 100m,
                            DeptId = 1,
                            Description = "Learn basics of programming",
                            MinDegree = 50m,
                            Name = "Intro Programming",
                            Topic = "Programming"
                        },
                        new
                        {
                            Num = 2,
                            Degree = 100m,
                            DeptId = 1,
                            Description = "Study of data organization",
                            MinDegree = 50m,
                            Name = "Data Structures",
                            Topic = "Computer Science"
                        },
                        new
                        {
                            Num = 3,
                            Degree = 100m,
                            DeptId = 1,
                            Description = "Relational databases and SQL",
                            MinDegree = 50m,
                            Name = "Database Systems",
                            Topic = "Databases"
                        },
                        new
                        {
                            Num = 4,
                            Degree = 100m,
                            DeptId = 1,
                            Description = "HTML, CSS, JavaScript, ASP.NET",
                            MinDegree = 50m,
                            Name = "Web Development",
                            Topic = "Web"
                        },
                        new
                        {
                            Num = 5,
                            Degree = 100m,
                            DeptId = 1,
                            Description = "Introduction to ML algorithms",
                            MinDegree = 50m,
                            Name = "Machine Learning",
                            Topic = "AI"
                        });
                });

            modelBuilder.Entity("FullstackMVC.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MangerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PcNumbers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Building A",
                            MangerName = "Dr. Ahmed Ali",
                            Name = "Computer Science",
                            PcNumbers = 50
                        },
                        new
                        {
                            Id = 2,
                            Location = "Building B",
                            MangerName = "Dr. Sara Hassan",
                            Name = "Engineering",
                            PcNumbers = 40
                        },
                        new
                        {
                            Id = 3,
                            Location = "Building C",
                            MangerName = "Dr. Mohamed Farid",
                            Name = "Business Administration",
                            PcNumbers = 30
                        });
                });

            modelBuilder.Entity("FullstackMVC.Models.Employee", b =>
                {
                    b.Property<int>("SSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SSN"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("SSN");

                    b.HasIndex("DeptId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FullstackMVC.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseNum")
                        .HasColumnType("int");

                    b.Property<decimal?>("GradeValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StudentSSN")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseNum");

                    b.HasIndex("StudentSSN");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseNum = 1,
                            GradeValue = 85m,
                            StudentSSN = 1001
                        },
                        new
                        {
                            Id = 2,
                            CourseNum = 2,
                            GradeValue = 90m,
                            StudentSSN = 1001
                        },
                        new
                        {
                            Id = 3,
                            CourseNum = 3,
                            GradeValue = 88m,
                            StudentSSN = 1001
                        },
                        new
                        {
                            Id = 4,
                            CourseNum = 1,
                            GradeValue = 92m,
                            StudentSSN = 1002
                        },
                        new
                        {
                            Id = 5,
                            CourseNum = 2,
                            GradeValue = 95m,
                            StudentSSN = 1002
                        },
                        new
                        {
                            Id = 6,
                            CourseNum = 4,
                            GradeValue = 89m,
                            StudentSSN = 1002
                        },
                        new
                        {
                            Id = 7,
                            CourseNum = 2,
                            GradeValue = 78m,
                            StudentSSN = 1003
                        },
                        new
                        {
                            Id = 8,
                            CourseNum = 3,
                            GradeValue = 82m,
                            StudentSSN = 1003
                        },
                        new
                        {
                            Id = 9,
                            CourseNum = 1,
                            GradeValue = 88m,
                            StudentSSN = 1004
                        },
                        new
                        {
                            Id = 10,
                            CourseNum = 3,
                            GradeValue = 91m,
                            StudentSSN = 1004
                        },
                        new
                        {
                            Id = 11,
                            CourseNum = 4,
                            GradeValue = 87m,
                            StudentSSN = 1004
                        },
                        new
                        {
                            Id = 12,
                            CourseNum = 2,
                            GradeValue = 75m,
                            StudentSSN = 1005
                        },
                        new
                        {
                            Id = 13,
                            CourseNum = 5,
                            GradeValue = 80m,
                            StudentSSN = 1005
                        },
                        new
                        {
                            Id = 14,
                            CourseNum = 1,
                            GradeValue = 93m,
                            StudentSSN = 1006
                        },
                        new
                        {
                            Id = 15,
                            CourseNum = 4,
                            GradeValue = 90m,
                            StudentSSN = 1006
                        },
                        new
                        {
                            Id = 16,
                            CourseNum = 3,
                            GradeValue = 84m,
                            StudentSSN = 1007
                        },
                        new
                        {
                            Id = 17,
                            CourseNum = 4,
                            GradeValue = 86m,
                            StudentSSN = 1007
                        },
                        new
                        {
                            Id = 18,
                            CourseNum = 1,
                            GradeValue = 96m,
                            StudentSSN = 1008
                        },
                        new
                        {
                            Id = 19,
                            CourseNum = 2,
                            GradeValue = 94m,
                            StudentSSN = 1008
                        },
                        new
                        {
                            Id = 20,
                            CourseNum = 5,
                            GradeValue = 92m,
                            StudentSSN = 1008
                        });
                });

            modelBuilder.Entity("FullstackMVC.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("CourseNum")
                        .HasColumnType("int");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CourseNum");

                    b.HasIndex("DeptId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Egypt",
                            Age = 45,
                            Degree = "PhD",
                            DeptId = 1,
                            Email = "amr.khaled@university.edu",
                            Name = "Dr. Amr Khaled",
                            Salary = 8000m
                        },
                        new
                        {
                            Id = 2,
                            Address = "Alexandria, Egypt",
                            Age = 40,
                            Degree = "PhD",
                            DeptId = 1,
                            Email = "mona.sayed@university.edu",
                            Name = "Dr. Mona Sayed",
                            Salary = 7500m
                        },
                        new
                        {
                            Id = 3,
                            Address = "Giza, Egypt",
                            Age = 38,
                            Degree = "PhD",
                            DeptId = 2,
                            Email = "yasser.ibrahim@university.edu",
                            Name = "Dr. Yasser Ibrahim",
                            Salary = 7000m
                        },
                        new
                        {
                            Id = 4,
                            Address = "Mansoura, Egypt",
                            Age = 42,
                            Degree = "PhD",
                            DeptId = 3,
                            Email = "hanan.mahmoud@university.edu",
                            Name = "Dr. Hanan Mahmoud",
                            Salary = 7200m
                        });
                });

            modelBuilder.Entity("FullstackMVC.Models.Student", b =>
                {
                    b.Property<int>("SSN")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SSN");

                    b.HasIndex("DeptId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            SSN = 1001,
                            Address = "Cairo, Egypt",
                            Age = 20,
                            DeptId = 1,
                            Gender = "Male",
                            Name = "Ahmed Mohamed"
                        },
                        new
                        {
                            SSN = 1002,
                            Address = "Alexandria, Egypt",
                            Age = 21,
                            DeptId = 1,
                            Gender = "Female",
                            Name = "Fatma Hassan"
                        },
                        new
                        {
                            SSN = 1003,
                            Address = "Giza, Egypt",
                            Age = 22,
                            DeptId = 2,
                            Gender = "Male",
                            Name = "Omar Khaled"
                        },
                        new
                        {
                            SSN = 1004,
                            Address = "Mansoura, Egypt",
                            Age = 20,
                            DeptId = 1,
                            Gender = "Female",
                            Name = "Nour Elsayed"
                        },
                        new
                        {
                            SSN = 1005,
                            Address = "Tanta, Egypt",
                            Age = 23,
                            DeptId = 2,
                            Gender = "Male",
                            Name = "Karim Ali"
                        },
                        new
                        {
                            SSN = 1006,
                            Address = "Aswan, Egypt",
                            Age = 21,
                            DeptId = 3,
                            Gender = "Female",
                            Name = "Mariam Youssef"
                        },
                        new
                        {
                            SSN = 1007,
                            Address = "Luxor, Egypt",
                            Age = 22,
                            DeptId = 3,
                            Gender = "Male",
                            Name = "Youssef Mahmoud"
                        },
                        new
                        {
                            SSN = 1008,
                            Address = "Port Said, Egypt",
                            Age = 20,
                            DeptId = 1,
                            Gender = "Female",
                            Name = "Heba Ahmed"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FullstackMVC.Models.ApplicationUser", b =>
                {
                    b.HasOne("FullstackMVC.Models.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId");

                    b.HasOne("FullstackMVC.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentSSN");

                    b.Navigation("Instructor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FullstackMVC.Models.Course", b =>
                {
                    b.HasOne("FullstackMVC.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FullstackMVC.Models.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("FullstackMVC.Models.Employee", b =>
                {
                    b.HasOne("FullstackMVC.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DeptId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FullstackMVC.Models.Grade", b =>
                {
                    b.HasOne("FullstackMVC.Models.Course", "Course")
                        .WithMany("Grades")
                        .HasForeignKey("CourseNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FullstackMVC.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentSSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FullstackMVC.Models.Instructor", b =>
                {
                    b.HasOne("FullstackMVC.Models.Course", null)
                        .WithMany("Instructors")
                        .HasForeignKey("CourseNum");

                    b.HasOne("FullstackMVC.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DeptId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FullstackMVC.Models.Student", b =>
                {
                    b.HasOne("FullstackMVC.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DeptId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FullstackMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FullstackMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FullstackMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FullstackMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FullstackMVC.Models.Course", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("FullstackMVC.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Employees");

                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("FullstackMVC.Models.Instructor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("FullstackMVC.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });
        }
    }
}
